config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # static pages
  root 'static#index'
  get '/about', to: 'static#about'
  get '/contact', to: 'static#contact'
  post '/subscribe', to: 'static#subscribe'
  get '/events', to: 'events#index'
  get '/events/past', to: 'events#past'

  resources :project, :only => [:index, :show] do
    collection do
      get :research
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  before_validation :check_for_existence, :check_for_duplicate
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

private
  def check_for_existence
    return false if !self.email.present?
  end

  def check_for_duplicate
    return !User.find_by_email(self.email).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @imgList = ["gm.jpg", "gm.jpg"]
    @q = get_events
    @events = get_events.select { |hash| hash["start_time"] > Time.now.beginning_of_day }
  end

  def past
    @imgList = ["gm.jpg", "kaggle.jpg", "numenta.jpg","data_viz.jpg", "matlab.jpg", "gm.jpg", "gm.jpg"]
    @events = get_events.select { |hash| hash["start_time"] < Time.now.beginning_of_day }
  end

private
  def get_events
    graph = Koala::Facebook::API.new(Figaro.env.fb_api_key)
    events = graph.get_object("v2.5/1701763616733787/events")
  end

end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def index
    @projects = Project.where(tag: 'industry')
  end

  def show
    @project = Project.find(params[:id])
  end

  def research
    @projects = Project.where(tag: 'research')
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def index
    @selected_projs = Project.last(7)
  end

  def about
  end

  def contact
  end

  def subscribe
    @user = User.new(user_params)
    if @user.save
      SubscribeMailer.welcome_user(@user).deliver_now
      redirect_to root_path, flash: {success: "You have been subscribed to our mailing list!"}
    else
      redirect_to root_path, flash: {error: "You have already signed up!"}
    end
  end

private
  def user_params
    params.require(:user).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/events/index.html.slim
div class="row"
  div class="small-4 columns"
    h5
      div class="headers"
        h6
          a(href="/events/past")<< Previous Events
  div class="small-4 columns end"
    center
      h3
        div class="headers"
          |Upcoming Events

div class="row events"
  - if !@events.empty?
    - (0..@events.length-1).to_a.each do |ind|
      div class="small-12 medium-6 large-4 columns end"
        div class="card"
          .card-img
            = link_to "http://www.facebook.com/events/#{@events[ind]["id"]}"
              =image_tag (@imgList[ind])
          div class="card-content card-proj"
            = @events[ind]["name"]
            br
            = DateTime.parse(@events[ind]["start_time"]).strftime("%a, %b %d")
            br
            br
            b = @events[ind]["place"]["name"]
            div class="small-push-8"
              a class="hollow button" href="http://www.facebook.com/events/#{@events[ind]["id"]}" >> Details
  - else
    | We don't have any upcoming events

app/views/events/past.html.slim
div class="row"
  div class="small-4 columns"
    h5
      div class="headers"
        h6
          a(href="/events")<< Current Events
  div class="small-4 columns end"
    center
      h3
        div class="headers" Past Events

div class="row events"
  - if !@events.empty?
    - (0..@events.length-1).to_a.each do |ind|
      center
        #modal
          .modal-content
            .header
              h3 Event name
            .copy
              h5 More things coming here
              a href="#"  X Close
          .overlay

      div class="small-12 medium-6 large-4 columns end"
        div class="card"
          .card-img
            = link_to "http://www.facebook.com/events/#{@events[ind]["id"]}"
              =image_tag @imgList[ind]
          div class="card-content card-proj"
            b = @events[ind]["name"]
            br
            = DateTime.parse(@events[ind]["start_time"]).strftime("%a, %b %d")
            br
            = @events[ind]["place"]["name"]
            br
            br
            div class="small-push-8"
              a class="hollow button" href="http://www.facebook.com/events/#{@events[ind]["id"]}" >> Details
  - else
    | We don't have any past events.

app/views/layouts/_flash.html.slim
-flash.each do |key, value|
  div class="alert-box #{key}" data-alert=""
    = value

app/views/layouts/_footer.html.slim
footer
  div class="row"
    div class="small-12 large-4 columns"
      h6
        | Machine Learning at Berkeley
        br
        | Talk to us: ml.at.berkeley@gmail.com

app/views/layouts/_header.html.slim
.top-bar#top-bar
  .row
    .top-bar-left.medium-horizontal
      .logo
        a(href="/") ML@B
    .top-bar-right
      ul.dropdown.vertical.medium-horizontal.menu
        li: a(href="/about") About
        li: a(href="/events") Events
        li: .drop
          a(href="#")
            | Portfolio
            .drop-container
              .drop-elem
                = link_to "Industry", project_index_path
                br
              .drop-elem
                = link_to "Research", research_project_index_path

app/views/layouts/_modal.html.slim
<div class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 class="modal-heading">Modal header</h3>
  </div>
  <div class="modal-body">
    <p>One fine body…</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
    <a href="#" class="btn btn-primary">Add to Cart</a>
  </div>
</div>

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "ML@B"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    link href="https://fonts.googleapis.com/css?family=Ubuntu:400,300,500" rel="stylesheet" type="text/css"
    = csrf_meta_tag

  body
    == render 'layouts/header'
    == render 'layouts/flash'
    .contents
      == yield
    == render 'layouts/footer'

app/views/project/index.html.slim
.row
  ul.breadcrumbs
    li: a(href="/") Home
    li: a(href="#") Portfolio
    li: a(href="/project") Industry
  h3
    div class="headers" About
  h6
    | Machine Learning at Berkeley's consulting branch allows members to work together with non-profits and companies to tackle challenging real world problems with the use of machine learning and data science. Each consulting project consists of around 8-10 members and lasts one semester. Through the ML@B consulting projects, members gain the experience to solve machine learning and data science problems in industry.

  - for project in @projects
   = link_to project
    .small-12.medium-6.large-4.columns.end
      .card.card-proj
        .card-img
          = image_tag project.img_url
        .card-content
          b = project.name
          '  |
          = project.tag
          br
          .descrip
            = project.description
            = link_to project

app/views/project/research.html.slim
.row
  ul.breadcrumbs
    li: a(href="/") Home
    li: a(href="/project") Portfolio
    li: a(href="/project/research") Research
  h3
    div class="headers" About
  h6
    | Machine Learning at Berkeley's research division seeks to provide a platform for students and faculty to collaborate outside of the context of the many AI/ML research laboratories at Berkeley. We believe that landmark research in machine learning almost always comes from left field, and we cherish and encourage novelty in our division.
    br
    | Our projects and papers are proposed by students and then backed over the course of each academic year into fully fledged research teams. The proposal process leads to a diverse group of projects each year exploring areas from deep reinforcement learning to statistical machine learning, harnessing the creativity and unique backgrounds of our members.

  - for project in @projects
   = link_to project
    .small-12.medium-6.large-4.columns.end
      .card.card-proj
        .card-img
          = image_tag project.img_url
        .card-content
          b = project.name
          '    |
          = project.tag
          br
          .descrip
            =project.description
            |...
            link_to project | ...

app/views/project/show.html.slim
.row
  ul.breadcrumbs
    li: a(href="/") Home
    li: a(href="#") Portfolio
    li: a(href="/project") Industry
    li: a(href="#")
      =@project.name
  .small-12.wide
    center
      =image_tag @project.img_url
    br
    h3
      =@project.name
    | Description:
    h6
      =@project.description